box/box-annotations

src/controllers/DrawingModeController.js, src/controllers/__tests__/DrawingModeController-test.js, src/doc/DocDrawingThread.js, src/drawing/DrawingThread.js
- Annotations should only be registered with the controller on save when
the location is finalized. They no longer need to be saved in the
annotator threadMap, therefore we no longer care when the location was
initially assigned
=> Fix: Only registering thread with controller on save

src/doc/DocAnnotator.js, src/doc/__tests__/DocAnnotator-test.js
Highlight gets removed so there is no longer a selection to create a highlight, therefore the createHighlightDialog should be hidden and cleared on mobile zoom
=> Fix: Hide createHighlightDialog on mobile page re-render

src/Annotator.scss
Fixes width of reply text area from this
=> Fix: Match width of reply textarea with comments

src/AnnotationDialog.js, src/Annotator.js, src/CommentBox.js, src/CreateAnnotationDialog.js, src/MobileAnnotator.scss, src/__tests__/AnnotationDialog-test.js, src/__tests__/Annotator-test.js, src/__tests__/CommentBox-test.js, src/__tests__/CreateAnnotationDialog-test.js, src/annotationConstants.js, src/controllers/AnnotationModeController.js, src/controllers/DrawingModeController.js, src/controllers/PointModeController.js, src/controllers/__tests__/DrawingModeController-test.js, src/controllers/__tests__/PointModeController-test.js, src/doc/CreateHighlightDialog.js, src/doc/DocAnnotator.js, src/doc/DocPointThread.js, src/doc/__tests__/CreateHighlightDialog-test.js, src/doc/__tests__/DocAnnotator-test.js, src/doc/__tests__/DocPointThread-test.js, src/image/ImagePointThread.js, src/image/__tests__/ImagePointThread-test.js
Initial PR comments https://github.com/box/box-annotations/pull/3 that was auto-closed by Github
=> Fix: Only show create dialog when creating new point annotations

src/Annotation.js, src/AnnotationDialog.js, src/AnnotationService.js, src/AnnotationThread.js, src/Annotator.js
Removed from: 
- Annotation.js
- AnnotationService.js
- Annotator.js
- AnnotationThread.js
- AnnotationDialog.js
=> Chore: Remove autobind from base classes

src/AnnotationDialog.js, src/AnnotationThread.js, src/__tests__/AnnotationDialog-test.js, src/__tests__/AnnotationThread-test.js, src/doc/__tests__/DocHighlightThread-test.js
This prevents users from performing actions on annotations that haven't saved on the server yet.
=> Chore: Disable dialog actions until annotation is saved on the server

src/doc/DocPointThread.js, src/doc/__tests__/DocPointThread-test.js, src/image/ImagePointThread.js, src/image/__tests__/ImagePointThread-test.js
* Dialogs are already positioned once in dialog.show() so calling dialog.position() afterwards on desktop browsers is redundant
=> Chore: Remove redundant point dialog positioning

build/publish.sh, build/release.sh
Since npm does not allow the publishing of existing versions, the publish script will assume the latest version is the desired version and reset to that tag rather than to master. This fixes the case where the publish script would reset to master on a patch release, which would result in attempting to publish the previous minor version rather than the desired patch version.
=> Fix: Publish script to reset to latest tag instead of to master

src/Annotator.js, src/__tests__/Annotator-test.js, src/doc/DocAnnotator.js, src/doc/__tests__/DocAnnotator-test.js
When plain and comment highlights are disabled and point annotations were enabled, the proper controllers and listeners were not set up.
=> Fix: Ensure point annotations are set up even when highlights are disabled

src/Annotator.js, src/__tests__/Annotator-test.js, src/__tests__/util-test.js, src/doc/CreateHighlightDialog.js, src/doc/DocAnnotator.js, src/doc/__tests__/CreateHighlightDialog-test.js, src/util.js
* Using the last annotation to determine whether or not the current annotation is of a valid and enabled type is problematic because because highlight comment annotations may have a plain highlight as the first annotation in the thread, resulting in a false positive for the thread.
* Fixes bug where both highlight and comment buttons were displayed in the create dialog despite only plain highlights being enabled
=> Fix: Clarify separation between plain and comment highlights

src/doc/__tests__/docUtil-test.js, src/doc/docUtil.js
- The annotations layer is inserted before the text layer which does not exist when the user doesn't have download permissions.
=> Fix: Ensure annotation layer is before point annotations

src/BoxAnnotations.js, src/__tests__/BoxAnnotations-test.js
Dependent on https://github.com/box/box-content-preview/pull/539
This will allow a developer to instantiate annotations outside of Preview like this: 
```
const options = {
Image: {
enabled: true
},
// Document/Presentation Annotators are the same so the config is simplified here
Document: {
enabledTypes: ['highlight', 'draw']
}
};
/* global BoxAnnotations */
const boxAnnotations = new BoxAnnotations(options);
var preview = new Box.Preview();
preview.show(FILE_ID, ACCESS_TOKEN, {
container: '.preview-container',
showDownload: true,
boxAnnotations
});
```
=> New: Allow BoxAnnotations to be instantiated independently and passed into Preview as an option

src/AnnotationDialog.js, src/__tests__/AnnotationDialog-test.js, src/__tests__/util-test.js, src/util.js
- Validate text areas when you cancel an annotations reply
=> Fix: Scroll to bottom of mobile dialogs

src/controllers/DrawingModeController.js, src/controllers/__tests__/DrawingModeController-test.js, src/doc/DocDrawingThread.js, src/doc/__tests__/DocDrawingThread-test.js
This PR and https://github.com/box/box-annotations/pull/87 fix https://github.com/box/box-annotations/issues/86
=> Fix: Safety checks if no threads are registered in the draw controller

src/Annotator.scss
The margins for each `<p>` tag inside the comment in addition to the `<br\>` tags caused double newline breaks to appear in the comments
=> Fix: Extra padding on escaped comment newlines

src/AnnotationDialog.js, src/__tests__/AnnotationDialog-test.js
This would cause `dialog.scrollToLastComment()` to be called even after the creation of a new annotation was cancelled. This method should only be called on cancel when cancelling a reply not a new annotation
=> Fix: Don't deactivate dialog when canceling new annotation

src/constants.js, src/controllers/HighlightModeController.js, src/controllers/__tests__/HighlightModeController-test.js, src/doc/DocAnnotator.js, src/doc/__tests__/DocAnnotator-test.js
- Ensures that when a plain highlight that was converted into a highlight comment is deleted, the correct canvas is cleared and re-rendered
=> Fix: Clear both highlight canvases when deleting highlights

src/Annotator.js, src/__tests__/Annotator-test.js, src/constants.js, src/controllers/HighlightModeController.js, src/controllers/__tests__/HighlightModeController-test.js, src/doc/DocHighlightThread.js
Fixes issue caused when the page is resized while creating a point annotation on mobile (from #71)
=> Fix: Do not destroy pending point threads on mobile re-render

src/Annotator.js, src/__tests__/Annotator-test.js, src/doc/DocAnnotator.js, src/doc/__tests__/DocAnnotator-test.js, src/image/ImageAnnotator.js, src/image/__tests__/ImageAnnotator-test.js
- Use the proper mouse event for point annotations in getLocationFromEvent
- Hide the mobile dialog on outside click for highlight annotations
=> Fix: Mobile cleanup

src/Annotator.js, src/__tests__/Annotator-test.js, src/__tests__/util-test.js, src/util.js
- Threads should be accessed from rbush trees rather than arrays.
=> Fix: Cleanup page thread access methods

src/CommentBox.js, src/__tests__/CommentBox-test.js
Closes https://github.com/box/box-annotations/issues/110
=> Fix: Create point dialog doesn't stop propagating click event on mobile

package.json
Since box-annotations isn't meant to be imported from npm as a node module, it doesn't need any package.json dependencies. Moving box-react-ui, rangy, and rbush to devDependencies fixes peer dependency warnings in preview.
=> Fix: Move dependencies to dev dependencies

src/AnnotationThread.js, src/__tests__/AnnotationThread-test.js, src/controllers/DrawingModeController.js, src/controllers/__tests__/DrawingModeController-test.js, src/doc/DocAnnotator.js, src/drawing/DrawingThread.js, src/drawing/__tests__/DrawingThread-test.js
Fixes the following issues: 
1. Drawing a second annotation after saving a previous one will continue adding the drawings to the previous path. 
2. Error notification was thrown on "touchend" for invalid locations
=> Fix: Draw annotation mode bugs

README.md
- Removing the section which demonstrated how to instantiate Annotators. This logic is performed inside Preview and therefore not relevant to developers using BoxAnnotations on it's own
=> Chore: Cleanup instantiation documentation in README

src/doc/DocDrawingThread.js, src/doc/DocHighlightThread.js, src/doc/__tests__/DocDrawingThread-test.js, src/drawing/DrawingThread.js, src/drawing/__tests__/DrawingThread-test.js
Fixes bug where drawing boundary was not re-drawn when a drawing was added to an already pending drawing.
=> Fix: Re-draw drawing thread boundary on path change

src/AnnotationDialog.js, src/AnnotationThread.js, src/CommentBox.js, src/CreateAnnotationDialog.js, src/__tests__/AnnotationDialog-test.js, src/__tests__/AnnotationThread-test.js, src/controllers/AnnotationModeController.js, src/controllers/__tests__/AnnotationModeController-test.js, src/doc/DocHighlightThread.js, src/doc/DocPointThread.js, src/image/ImagePointThread.js
- Instantiates all annotation dialogs with the proper variables for isMobile/hasTouch
- Binds touch events to annotation dialogs on touch enabled desktop devices
- Hides all newly created non-pending dialogs on touch enabled desktop devices
=> Fix: Ensure isMobile and hasTouch gets passed on to all dialogs

src/__tests__/util-test.js, src/controllers/AnnotationModeController.js, src/controllers/DrawingModeController.js, src/controllers/__tests__/AnnotationModeController-test.js, src/controllers/__tests__/DrawingModeController-test.js, src/controllers/__tests__/HighlightModeController-test.js, src/doc/DocDrawingThread.js, src/doc/__tests__/DocDrawingThread-test.js, src/drawing/DrawingThread.js, src/drawing/__tests__/DrawingThread-test.js, src/util.js
- Fixes issue where users couldn't select drawings after pressing the "Done" button
- Drawing handlers require a blank temporary thread in order to actually start/stop drawing. This thread is not yet saved into the API and will not have valid location information until the user actually begins drawing. This prevents the controller from saving that empty thread until it contains valid location information.
- Validates min/max boundary coordinates for annotation threads
=> Fix: Don't save empty drawing threads

src/AnnotationDialog.js, src/CreateAnnotationDialog.js, src/__tests__/AnnotationDialog-test.js, src/__tests__/CreateAnnotationDialog-test.js, src/controllers/DrawingModeController.js, src/controllers/__tests__/DrawingModeController-test.js, src/doc/DocDrawingDialog.js, src/doc/__tests__/DocDrawingDialog-test.js
- Fixes situation where touch events are improperly bound in the shared mobile annotation dialog.
=> Fix: Binds handlers appropriately for desktop/touch/mobile devices

src/controllers/DrawingModeController.js, src/controllers/__tests__/DrawingModeController-test.js
Currently users are able to select existing drawings while in the process of drawing a new annotation. This can cause an additional annotation dialog to stay open in the background in addition to the dialog for the new unsaved drawing. This commit does not trigger any saved annotation dialogs while drawing.
=> Chore: Don't allow selection of saved thread in draw mode

src/AnnotationDialog.js, src/AnnotationThread.js, src/Annotator.js, src/__tests__/AnnotationDialog-test.js, src/__tests__/AnnotationThread-test.js, src/__tests__/Annotator-test.js, src/__tests__/util-test.js, src/constants.js, src/doc/CreateHighlightDialog.js, src/doc/DocAnnotator.js, src/doc/DocHighlightThread.js, src/doc/__tests__/DocAnnotator-test.js, src/util.js
- Simplified some of the logic triggered by closing either mobile point or highlight dialogs. 
- Fixes issue where the mobile highlight comment dialog didn't close on clicking the 'X' button
=> Fix: Cleanup hiding/closing of the mobile dialog

src/AnnotationDialog.js, src/__tests__/AnnotationDialog-test.js
- Fixes issue where  mobile annotation dialog flickers for a while when user clicks on 'Delete' or 'Cancel" button while deleting comments added via "Point Annotation" method
=> Fix: Mobile dialog doesn't properly close on delete cancel/confirm

src/controllers/AnnotationModeController.js, src/controllers/DrawingModeController.js, src/controllers/PointModeController.js, src/controllers/__tests__/DrawingModeController-test.js, src/controllers/__tests__/PointModeController-test.js, src/doc/DocDrawingThread.js, src/doc/__tests__/DocDrawingThread-test.js, src/drawing/DrawingThread.js, src/drawing/__tests__/DrawingThread-test.js
- Required to enable drawing annotations on image files
=> Chore: Removing DrawingModeController dependency on DocDrawingThread

src/AnnotationDialog.js
This issue was caused because toElement is not supported in firefox, thus was returning undefined and was being replaced with event.target in a later method, which is the dialog itself. Replaced with relatedTarget which is cross browser
=> Fix: firefox dialog collapse on mouseout

functional-tests/helpers/constants.js, functional-tests/helpers/mouseEvents.js, functional-tests/tests/draw.js, functional-tests/tests/plain_highlight.js
Dependent on https://github.com/box/box-annotations/pull/179/
=> Chore: Add tests to select/delete drawing

functional-tests/helpers/actions.js, functional-tests/helpers/constants.js, functional-tests/helpers/validation.js, functional-tests/tests/draw.js, functional-tests/tests/highlight_comment.js, functional-tests/tests/plain_highlight.js, functional-tests/tests/point.js, functional-tests/views/index.pug, src/constants.js
- Create/Cancel/Delete a highlight comment annotation
- Enter/Exit point annotation mode
- Create/Delete a point annotation
- Create/Delete replies to highlight comment/point annotations
=> New: Add basic UI tests for point & highlight comment annotations

src/controllers/PointModeController.js, src/controllers/__tests__/PointModeController-test.js
- Attempting to create a point annotation on top of an existing point annotation will close the dialog.
- Initially only the point annotation icon would be removed but the dialog would remain with no way of closing it
=> Fix: Mobile point annotation behavior

src/Annotator.scss
Cursor should be overridden with `auto` instead of `default` since `default` just uses an arrow for everything.
=> Fix: Cursor type in annotation dialog

src/Annotator.scss
=> Chore: break all text to fit into dialog

src/doc/DocAnnotator.js
In the `clickHander`, we don't want to stop event propagation because that that will keep the events from bubbling up to the React listeners on the document
=> Fix: Create Mobile Doc Point Annotation

src/controllers/AnnotationModeController.js
Properly unregisters threads when the user previews multiple files consecutively
=> Fix: Binding of controller.unregisterThread on destroy

src/AnnotationThread.js, src/doc/DocHighlightThread.js
- Deletes the entire highlight when the user has permissions to delete both the last comment and the entire highlight annotation OR if the current annotation is a plain highlight
- Only deletes the last comment on the highlight if the user does not have permissions to delete the entire highlight annotation
- Otherwise just deletes the comment and re-renders the popover
=> Fix: Deletion of entire highlight when last comment is deleted

src/AnnotationThread.js, src/Annotator.js, src/__tests__/AnnotationThread-test.js, src/__tests__/Annotator-test.js, src/constants.js, src/controllers/AnnotationModeController.js, src/controllers/DrawingModeController.js, src/controllers/__tests__/AnnotationModeController-test.js, src/controllers/__tests__/DrawingModeController-test.js, src/doc/DocAnnotator.js, src/doc/DocHighlightThread.js, src/doc/__tests__/DocHighlightThread-test.js, src/drawing/DrawingThread.js, src/drawing/__tests__/DrawingThread-test.js
=> Fix: Ensure drawings are only registered once with the controller

src/controllers/AnnotationModeController.js, src/controllers/__tests__/AnnotationModeController-test.js
- This is a fix specifically for Annotations in the ContentPreview element or other cases when the header element is not contained inside box-content-preview
=> Fix: Get mode button from header element rather than container

src/AnnotationThread.js, src/__tests__/AnnotationThread-test.js, src/constants.js, src/controllers/AnnotationModeController.js, src/controllers/DrawingModeController.js, src/controllers/__tests__/AnnotationModeController-test.js, src/controllers/__tests__/DrawingModeController-test.js
- Prevents new annotations (drawings) that are created before the create API call has successfully returned from being appended onto previous annotations (drawings)
=> Fix: Reset current annotation thread immediately on save

functional-tests/helpers/actions.js, functional-tests/helpers/validation.js, functional-tests/tests/draw.js, functional-tests/tests/plain_highlight.js
- Add test to ensure highlighting works even after interacting w/ drawing/point modes
=> Fix: Functional tests

src/doc/DocAnnotator.js, src/doc/__tests__/DocAnnotator-test.js
- Only reset highlight selection on `selectionchange` event on touch enabled devices when the user is NOT creating a highlight annotation
=> Fix: Highlight selection on Surface

i18n/en-US.properties, package.json, src/AnnotationThread.js, src/components/AnnotationPopover/AnnotationPopover.js, src/components/AnnotationPopover/__tests__/__snapshots__/AnnotationPopover-test.js.snap, src/components/AnnotationPopover/messages.js, src/doc/DocHighlightThread.js, yarn.lock
=> Chore: Add escape hotkey on AnnotationPopover

package.json, src/components/ActionControls/ActionControls.js, third-party/components/ApprovalCommentForm/ApprovalCommentForm.js, third-party/components/ApprovalCommentForm/ApprovalCommentForm.scss, third-party/components/ApprovalCommentForm/__tests__/ApprovalCommentForm-test.js, third-party/components/ApprovalCommentForm/__tests__/__snapshots__/ApprovalCommentForm-test.js.snap, yarn.lock
This duplication of ApprovalCommentForm replaces the DraftJSMentionSelector with a simple TextArea due to complications with Android autocomplete interfering with draft.js
See https://github.com/facebook/draft-js/issues/1895
=> Fix: Replacing DraftJSMentionSelector with TextArea

src/components/ActionControls/ActionControls.scss, src/components/ActionControls/DrawingControls.scss, src/components/ActionControls/HighlightControls.scss, src/components/AnnotationPopover/AnnotationPopover.scss, src/components/AnnotationPopover/AnnotatorLabel.scss
Visually this will look the same, however this will make the action control buttons cover more space, making it easier to click the actual button
Tested on all types of devices/dialogs that can appear (mobile/tablet/desktop)
=> Fix: Increase action control button padding

src/doc/DocHighlightThread.js, src/doc/__tests__/DocHighlightThread-test.js
- Toggles an annotation between a plain highlight and highlight comment based on the number of comments saved on the annotation at the time when the cancel button was clicked
=> Fix: Toggle highlight comment to plain highlight on cancel

src/AnnotationThread.js, src/__tests__/AnnotationThread-test.js, src/controllers/DrawingModeController.js, src/controllers/__tests__/DrawingModeController-test.js, src/doc/DocDrawingThread.js
Issue was that when starting a drawing annotation, in `DrawingModeController.drawingStartHandler` we would register the thread, which would make an entry into the rbush instance for that page, however the location would be of the mouse event point, not the finished drawing boundary. Upon refresh the whole boundary would be available and registered into rbush so clicking at that point wouldn't be a problem.
The solution here is to defer `registerThread` until we have successfully saved.
A change in experience is also that after the drawing annotation is saved, we unmount the popover
=> Fix: Unable to select drawing annotation after saving

src/AnnotationThread.js, src/__tests__/AnnotationThread-test.js, src/doc/DocPointThread.js, src/doc/__tests__/DocPointThread-test.js, src/image/ImagePointThread.js, src/image/__tests__/ImagePointThread-test.js
=> Fix: Ensure point annotations aren't scrolled out of view on focus

src/AnnotationThread.js, src/__tests__/AnnotationThread-test.js
Ensures newly created annotations are deleted appropriately when the create API request fails.
=> Fix: Cleanup thread when API requests fail

src/Annotator.js, src/controllers/PointModeController.js, src/controllers/__tests__/PointModeController-test.js
=> Fix: Hide all threads before creating a new point annotation

docs/index.html
It looks like this page gets deployed to https://opensource.box.com/box-annotations automatically, but the latest release of Annotations was still published under `lib` rather than `dist`. We'll need to change this back once we do another release from master.
=> fix(docs): Revert annotation asset paths used by example site

.travis.yml
E2E tests start failing for new annotations, so disable for now
=> chore: disable e2e tests

src/common/BaseAnnotator.ts, src/common/__mocks__/EventManager.ts, src/common/__tests__/BaseAnnotator-test.ts
Looks like Preview SDK makes a call to `annotator.removeAllListeners()`
=> feat(eventing): add removeAllListeners

src/common/BaseAnnotator.ts
Was causing a memory leak of listeners added by client libraries (preview SDK) because `undefined` was being proxied to `EventEmitter.removeAllListeners`
=> fix(baseannotator): remove argument form removeAllListeners

src/region/RegionAnnotations.tsx, src/region/__tests__/RegionAnnotations-test.tsx, src/region/__tests__/actions-test.ts, src/region/actions.ts
I was seeing some jank at higher scale ratios due to the loss of coordinate resolution during the draw phase.
=> fix(region): Batch region drawing and round on create to avoid jank

src/BoxAnnotations.ts, src/__tests__/BoxAnnotations-test.js
* Add options field that can be passed into the instance. These options then will be passed to the annotator in Preview SDK. In this case, we will want to pass intl to the instance and then that should get passed to content preview, or which ever consumer calls `determineAnnotator`. These options will then be passed to the annotator configs in Preview SDK and use the current `intl` framework
=> feat(i18n): add options field

src/common/BaseAnnotator.scss, src/common/BaseManager.ts, src/common/__tests__/BaseAnnotator-test.ts, src/document/DocumentAnnotator.ts, src/document/__tests__/DocumentAnnotator-test.ts, src/region/RegionAnnotation.scss, src/region/RegionAnnotations.tsx, src/region/RegionCreator.scss, src/region/RegionCreator.tsx, src/region/RegionList.tsx, src/region/RegionRect.scss, src/region/__mocks__/RegionRect.tsx, src/region/__mocks__/data.ts, src/region/__tests__/RegionAnnotation-test.tsx, src/region/__tests__/RegionAnnotations-test.tsx, src/region/__tests__/RegionContainer-test.tsx, src/region/__tests__/RegionCreator-test.tsx, src/region/__tests__/RegionList-test.tsx, src/region/__tests__/RegionManager-test.ts, src/region/__tests__/RegionRect-test.tsx, src/region/__tests__/actions-test.ts, src/region/__tests__/regionUtil-test.ts, src/region/actions.ts, src/region/regionUtil.ts
=> fix(regions): Use relative position and size to support dynamic reps

src/@types/events.ts, src/common/BaseAnnotator.ts, src/common/__tests__/BaseAnnotator-test.ts, src/document/DocumentAnnotator.ts, src/document/__tests__/DocumentAnnotator-test.ts, src/store/annotations/__mocks__/annotationsState.ts, src/store/annotations/__tests__/reducer-test.ts, src/store/annotations/__tests__/selectors-test.ts, src/store/annotations/actions.ts, src/store/annotations/reducer.ts, src/store/annotations/selectors.ts, src/store/annotations/types.ts, src/store/eventing/__tests__/init-test.ts, src/store/eventing/init.ts, src/store/eventing/middleware.ts
https://github.com/box/box-content-preview/pull/1224 depends on this change
=> feat(scroll): emit 'annotations_initialized' when annotations first initializes.

src/image/ImageAnnotator.scss
Fixes center-aligned collaborator names/email entries for image annotations.
=> fix(style): Reset image annotator layer styles inherited from parent

src/@types/events.ts, src/store/eventing/__tests__/mode-test.ts, src/store/eventing/middleware.ts, src/store/eventing/mode.ts
* Add middleware handler that will emit an `annotations_mode_change` when toggleAnnotationMode is dispatched.
=> feat(events): Add toggleAnnotationMode events

src/common/BaseAnnotator.ts, src/common/__tests__/BaseAnnotator-test.ts
Needs to merge https://github.com/box/box-ui-elements/pull/2249 first.
=> fix(log): Fix resin isCurrentFileVersion is always true

src/BoxAnnotations.ts, src/__tests__/BoxAnnotations-test.js, src/common/BaseAnnotator.ts, src/common/__tests__/BaseAnnotator-test.ts, src/document/DocumentAnnotator.ts, src/document/__tests__/DocumentAnnotator-test.ts
Depends on https://github.com/box/box-content-preview/pull/1241
=> feat(features): Features as an option

src/document/DocumentAnnotator.ts, src/document/__tests__/DocumentAnnotator-test.ts, src/document/__tests__/docUtil-test.ts, src/document/docUtil.ts, src/highlight/HighlightListener.ts, src/highlight/__tests__/HighlightListener-test.ts, src/highlight/index.ts, src/store/__mocks__/index.ts, src/store/selection/actions.ts
This PR addresses following feedbacks from product:
1. The promotion popup shouldn't show up during mouse dragging.
2. Debounce keyboard selection 500ms.
3. When there're multiple ranges in one selection, only care about the last one.
Todo:
=> feat(highlight): Improve selection logic

src/highlight/HighlightListener.ts, src/highlight/__tests__/HighlightListener-test.ts
If you make a quick text selection, you sometimes find that the text selection goes beyond the text. This could also cause a slight shift in the highlight promoter popup after the selection is finished
What happens is that `isMouseSelecting` is set to false on `mouseup`  but delays getting the text selection by 300ms -- meanwhile the debounced `selectionchange` event fires after 500ms and since `isMouseSelecting` is already set to false, it proceeds to grab the text selection before PDFJS has time to finish the enhanced text layer work.
=> feat(highlightlistener): Avoid get selection race

src/components/ReplyForm/ReplyFormContainer.tsx
https://formik.org/docs/api/withFormik#mappropstoerrors-props-props--formikerrorsvalues
Adding the `mapPropsToErrors` with an initial error allows the Post button to render disabled on the initial mount before the formik `validate` method kicks in.
=> feat(replyform): Avoid flash of enabled Post button

src/document/__tests__/docUtil-test.ts, src/document/docUtil.ts, src/highlight/HighlightAnnotations.tsx, src/highlight/HighlightContainer.tsx, src/highlight/__mocks__/data.ts, src/highlight/__tests__/HighlightAnnotations-test.tsx, src/highlight/__tests__/HighlightContainer-test.tsx, src/highlight/__tests__/HighlightListener-test.ts, src/highlight/__tests__/highlightUtil-test.ts, src/highlight/highlightUtil.ts, src/store/promoter/__mocks__/data.ts, src/store/promoter/__mocks__/promoterState.ts, src/store/promoter/__tests__/reducer-test.ts, src/store/promoter/__tests__/selectors-test.ts, src/store/promoter/actions.ts, src/store/promoter/reducer.ts, src/store/promoter/types.ts
=> feat(highlight): Promote and show staged highlight annotation

src/@types/events.ts, src/store/eventing/__tests__/staged-test.ts, src/store/eventing/middleware.ts, src/store/eventing/staged.ts
=> feat(eventing): Emit new annotations_staged_change event

src/@types/events.ts, src/store/eventing/__tests__/status-test.ts, src/store/eventing/middleware.ts, src/store/eventing/status.ts
Preview PR: https://github.com/box/box-content-preview/pull/1254
=> feat(eventing): Emit new creator_status_change event

src/highlight/HighlightList.scss
`pointer-events: all` was causing an issue in Presentation files where all the pages are overlayed on top of each other, `HighlightTarget` SVG accepting click events even though they weren't the visible Presentation page
=> fix(highlights): Change pointer-events for highlight svg to visible

src/store/common/__tests__/reducer-test.ts, src/store/common/reducer.ts
The FSM in Preview SDK maintains the source of truth. So there is no need to have extra logic for setting mode in annotations.
=> feat(mode): Remove toggle logic

test/index.html
E2E test is failing because https://github.com/box/box-annotations/pull/590 (Remove toggle logic) needs Preview version >= 2.51.0.
=> test(cypress): Bump Preview SDK version

src/highlight/__tests__/highlightUtil-test.ts, src/highlight/highlightUtil.ts, src/store/highlight/actions.ts
Attempted an improvement to the existing rect combining strategy. Previously, we would round the rect's y coordinate to the nearest integer and use that as the key to combine all of those rects into such "rows". 
This approach attempts to combine rects that have the y coordinate within a certain threshold (% of height).
An additional enhancement is that it also combines based on whether the x coordinate is also within a certain threshold (% of width).
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
=> feat(highlights): Better rect smoothing

src/common/BaseAnnotator.ts, src/common/__tests__/BaseAnnotator-test.ts, src/region/RegionAnnotations.tsx, src/region/RegionContainer.tsx, src/region/__tests__/RegionAnnotations-test.tsx, src/region/__tests__/RegionContainer-test.tsx, src/store/options/__tests__/selectors-test.ts, src/store/options/reducer.ts, src/store/options/selectors.ts, src/store/options/types.ts
This attempts to solve the problem that when discoverability feature is enabled, existing region annotations are not clickable anymore because the `RegionCreator` normally is on top of the `RegionList`. 
As a part of this commit, the `features` are committed to the redux store. 
A separate change would be needed in Preview SDK to turn off `pointer-events` for the region annotation targets and highlight annotation targets when in explicit create region mode. See: https://github.com/box/box-content-preview/pull/1262
TODO:
=> feat(discoverability): Reorder RegionCreator before RegionList

src/highlight/HighlightTarget.tsx, src/highlight/__tests__/HighlightTarget-test.tsx
Fixes an issue where the SVG anchor for the highlight annotation target never received focus. As a result, you would get into this situation where:
- You select a region annotation (`document.activeElement` is the region annotation button)
- Region annotation is set as active
- You select a highlight annotation (`document.activeElement` is the region annotation button)
- Highlight annotation is set as active
- You select the region annotation again (`document.activeElement` is the region annotation button)
- Highlight annotation remains active
**GIF of the issue:**
=> fix(highlights): Allows highlight anchors to receive focus

src/popup/PopupContainer.tsx, src/popup/PopupLayer.tsx, src/popup/__tests__/PopupContainer-test.tsx, src/popup/__tests__/PopupLayer-test.tsx
This solves the issue where toggling between annotation modes doesn't hide the `PopupReply`
=> fix(popuplayer): Ensure the staged type matches the mode

src/region/RegionAnnotations.tsx, src/region/RegionContainer.tsx, src/region/RegionCreator.tsx, src/region/__tests__/RegionAnnotations-test.tsx, src/region/__tests__/RegionCreator-test.tsx, src/store/eventing/__tests__/staged-test.ts, src/store/eventing/staged.ts
**Main Issue:**
When the user clicks down on a region area, `handleStart` is being called which causes the Region button to be toggled on. However, when they let go of the button, handleStop is not being fired.
**Solution:**
We will call handleAbort in handleStop if the shape is null. handleAbort will call `resetCreator` which should emit the `cancel` event that the FSM in Preview SDK will consume.
**Demo:**
=> fix(discoverability): click incorrectly toggles region creator mode

src/store/highlight/__tests__/reducer-test.ts, src/store/highlight/reducer.ts
The first selection is canceled by starting dragging, and the second selection is canceled by clicking
=> fix(highlight): Reset selection when creator status changes

src/region/RegionCreator.tsx, src/region/__tests__/RegionCreator-test.tsx
=> feat(region): Add threshold for drawing region

src/common/__mocks__/useOutsideEvent.ts, src/common/useOutsideEvent.ts, src/components/Popups/PopupHighlight.tsx, src/components/Popups/PopupHighlightError.tsx, src/components/Popups/__tests__/PopupHighlight-test.tsx, src/components/Popups/__tests__/PopupHighlightError-test.tsx, src/highlight/HighlightAnnotations.tsx, src/highlight/HighlightContainer.tsx, src/highlight/__tests__/HighlightAnnotations-test.tsx
=> fix(highlight): Remove selection when clicking anywhere outside of popup

src/store/creator/__tests__/reducer-test.ts, src/store/creator/reducer.ts
Whenever the `toggleAnnotationModeAction` is dispatched, we reset the creator store so that any previously staged annotation is cleared out. 
**Before**
**After**
=> fix(creator): Reset creator store when toggleAnnotationModeAction

.eslintrc.js, src/highlight/__tests__/HighlightAnnotations-test.tsx, src/highlight/__tests__/HighlightList-test.tsx, src/region/__tests__/RegionAnnotations-test.tsx
Disabling the non-null assertion eslint rule for tests
=> chore: Updating eslint rules to support non-null assertion in tests

src/common/BaseManager.ts, src/document/DocumentAnnotator.ts, src/document/__tests__/DocumentAnnotator-test.ts, src/highlight/HighlightCreatorManager.ts, src/highlight/HighlightManager.tsx, src/image/ImageAnnotator.ts, src/popup/PopupManager.tsx, src/region/RegionCreationManager.tsx, src/region/RegionManager.tsx
Pulling a lot of the repetitive `Manager` logic (constructor, destroy, style, insert, etc...) into a `BaseManager` class.
=> refactor(manager): BaseManager class

jest.config.js
Cleans up the warning when running the tests
```
jest-haste-map: duplicate manual mock found: data
The following files share their name; please delete one of them:
* <rootDir>/src/highlight/__mocks__/data.ts
* <rootDir>/src/region/__mocks__/data.ts
jest-haste-map: duplicate manual mock found: data
The following files share their name; please delete one of them:
* <rootDir>/src/region/__mocks__/data.ts
* <rootDir>/src/store/highlight/__mocks__/data.ts
jest-haste-map: duplicate manual mock found: index
The following files share their name; please delete one of them:
* <rootDir>/src/components/ReplyForm/__mocks__/index.ts
* <rootDir>/src/store/__mocks__/index.ts
```
=> chore(jest): Ignore mocks as modules

src/common/__tests__/BaseAnnotator-test.ts
Clean up the existing annotator before getting a new one.
This cleans up the following when running tests:
```
(node:6655) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scaleannotations listeners added to [EventManager]. Use emitter.setMaxListeners() to increase limit
(node:6655) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 annotations_active_set listeners added to [EventManager]. Use emitter.setMaxListeners() to increase limit
(node:6655) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 annotations_remove listeners added to [EventManager]. Use emitter.setMaxListeners() to increase limit
(node:6655) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 annotations_visible_set …
```
=> fix(tests): BaseAnnotator test emitter leak

src/highlight/__tests__/highlightUtil-test.ts, src/highlight/highlightUtil.ts
`Number.MIN_VALUE` is actually the smallest positive number closest to zero. Combined with negative y-axis values for client rects (which happens when the text selection is involved with a vertical page scroll) resulted in incorrect logic when attempting to smoothen and combine the rects.
=> fix(highlight): getBoundingRect to handle negative y-axis

src/@types/model.ts, src/common/useOutsideEvent.ts, src/drawing/DrawingList.tsx, src/drawing/DrawingPath.scss, src/drawing/DrawingPath.tsx, src/drawing/DrawingPathGroup.tsx, src/drawing/DrawingSVG.tsx, src/drawing/DrawingTarget.scss, src/drawing/DrawingTarget.tsx, src/drawing/__mocks__/drawingData.ts, src/drawing/__tests__/DrawingPath-test.tsx, src/drawing/__tests__/DrawingPathGroup-test.tsx, src/drawing/__tests__/DrawingSVG-test.tsx, src/drawing/__tests__/DrawingTarget-test.tsx, src/drawing/__tests__/drawingUtil-test.ts, src/drawing/drawingUtil.ts, src/store/annotations/__tests__/reducer-test.ts, src/store/annotations/reducer.ts
=> feat(drawing): Add drawing paths

src/drawing/DrawingAnnotations.scss
**Changes in this PR:**
**Demo:**
=> fix(drawing): hide drawing toolbar when user starts drawing

src/drawing/DrawingCreator.tsx, src/region/RegionCreator.tsx
There is a bug where if you create a region super quickly (you click the mouse and very quickly move and release the mouse) the `PopupReply` doesn't appear. This is because the `PointerCapture` `onDrawStop` callback is never called. 
On closer inspection, it is discovered that on every mouse move `PointerCapture` is re-rendering and as a result re-adding the listeners to the document to capture `mousemove` and `mouseup` events because `RegionCreator` is re-rendering due to state being updated.
The fix here is to use `React.useCallback` on all callback props being passed to `PointerCapture` to memoize the callback props so that `PointerCapture` doesn't need to re-render unless `drawingStatus` changes
=> fix(region): Memoize callback props passed to PointerCapture

src/drawing/DrawingCreator.tsx, src/drawing/__tests__/DrawingCreator-test.tsx
=> feat(drawing): Bound the drawing to the document dimensions

src/drawing/DrawingSVG.tsx
**Main Issue:**
We were seeing a bug where because we were using `primitiveUnits="objectBoundingBox"`, this was causing the annotated elements that were smaller to not have a prominent blur applied. Removing the primitiveUnits attribute + making the opacity darker helped solve this issue.
**Demo:**
**Chrome**
**Safari**
**Firefox**
**Edge**
**IE11**
=> fix(drawing): apply blur to smaller drawn annotations

src/drawing/DrawingSVG.tsx
**Changes in this PR:**
**Demo:**
Chrome
Safari
Firefox
Edge
IE
=> fix(drawing): fix drawing annotation blur clipping on bounding box

src/drawing/DrawingSVG.tsx
**Changes in this PR:**
**Demo:**
Chrome
Safari
Firefox
Edge
IE
=> fix(drawing): fix blur not showing in safari

src/components/Popups/PopupDrawingToolbar.scss
**Main Issue:**
**IE**
**Edge**
**Firefox**
**Chrome**
**Safari**
=> fix(drawing): fix Add Comment text wrapping in Safari

src/components/ItemList/ItemList.scss
**Main Issue:**
In IE, there was an text alignment issue with at-mentions. Text should be left-aligned rather than centered.
**Demo:**
=> fix(region): text alignment for at mentions in annotation popup in IE

src/components/ReplyField/ReplyField.tsx, src/components/ReplyField/__tests__/ReplyField-test.tsx
=> fix(reply): Fix at mention list misaligned after window resize

src/components/Popups/PopupReply.tsx, src/components/Popups/__tests__/PopupReply-test.tsx
A previous commit removed the functionality of the `PopupReply` automatically flipping if it would extend outside the viewport. This adds that functionality back, with the exception made for IE11 because of the issue where it gets covered by the next page of a document due to z-index issues.
=> fix(popupreply): Add back flip to keep within viewport

src/document/docUtil.ts
Fixing incorrect text selection/highlighting behavior specifically on Firefox. Tested other browsers as well just to be sure!
**Before (Firefox):**
**After (Firefox):**
=> fix(highlight): Fix text highlighting for PDFjs upgrade

src/document/DocumentAnnotator.ts
Due to changes in PDFjs v3.6.172, annotations would dissapear upon zooming in/out on the pdf. This is because the page elements that our annotation managers were referencing would be removed when zooming in/out. The textLayer pdfJS uses would not be removed however, which would make one of our managers not get cleaned up. In order to reinstantiate our managers, we need all managers to be cleaned up. Because of our current logic for adding managers, we need to make sure every manager is cleaned up when at least one manager is cleaned up. Which makes sense since the annotation managers are coupled together and cannot function correctly without the others.
Annotation Drawing mode
Annotation Highlight mode
=> fix(missing-annotations): Fix annotations on zoom issue

src/common/BaseAnnotator.scss, src/image/ImageAnnotator.scss
Moving annotation layer related stylings to this repository for better organization. These styling changes resolve issues found in the new PDFjs upgrade related to a change that they made to the z-index for the textLayer.
=> fix(styling): Fix annotation layer styling

i18n/en-US.properties, src/components/Popups/messages.ts, src/components/ReplyField/ReplyField.tsx, src/components/ReplyField/__tests__/ReplyField-test.tsx, src/components/ReplyField/__tests__/ReplyFieldContainer-test.tsx, src/components/ReplyForm/ReplyForm.tsx
=> fix(accessibility): Add accessible name for ReplyField

package.json, yarn.lock
After Node 18 upgrade there are some errors occurring. Upgrading jest-canvas-mock seems to fix the problem.
=> chore(tests): Fix cannot redefine property: window errors

package.json, scripts/webpack.config.js, yarn.lock
This PR replaces deprecated `uglifyjs-webpack-plugin` in favor of `terser-webpack-plugin`.  Running uglify causes build to error with:
```
ERROR in annotations.js from UglifyJs
Unexpected token: keyword «const» [annotations.js:831,0]
```
when running with `box-ui-elements@19` and later.
~NOTE: I wasn't able to run this build and verify if it still works yet.~ Annotations seem to work as before when testing locally with `yarn link`.
=> chore: replace uglify with terser

src/common/BaseAnnotator.scss
BUIE PR: https://github.com/box/box-ui-elements/pull/3499
The fonts files itself haven't changed.
Changing it to have parity with internal Box changes. This will cause the 1.0.2 fonts to not be downloaded, in favor of existing 1.0.17.
=> chore(fonts): update Lato fonts to point to 1.0.17

.travis.yml
e2e tests have been failing due to a timeout with 10 minutes without content written to the console ([docs](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received)). This PR increases the timeout to 30 minutes to give more time for tests to finish running.
=> fix(e2etest): Increase timeout to 30 minutes for e2e

.nvmrc, .travis.yml, browserslist, package.json, yarn.lock
Upgrading repository to work with node 20. 
Apart from configuration changes, I needed to add resolutions for acorn. For some reason older version started having problem with optional chaining operator. To properly upgrade dependencies webpack should be updated to next major version. Since this is the major change I decided to resolution for now.
=> feat(node-upgrade): Upgrade to node 20
