box/box-annotations

src/MobileAnnotator.scss, src/doc/DocAnnotator.js, src/doc/__tests__/DocAnnotator-test.js
Also fixes styling from this
to this behavior
=>  Fix: Hide mobile dialog on first outside click

src/Annotator.scss, src/CommentBox.js
Fixing some bugs due to merge conflicts that were resolved in #29
=> Fix: Ensure commentbox event listeners are bound properly

build/release.sh
Optimizing build/release scripts a little. Also see https://github.com/box/box-ui-elements/pull/88
=> Chore: Remove NPM install from release/publish scripts

src/Annotator.js, src/Annotator.scss, src/__tests__/Annotator-test.js, src/__tests__/util-test.js, src/controllers/AnnotationModeController.js, src/controllers/DrawingModeController.js, src/controllers/__tests__/AnnotationModeController-test.js, src/controllers/__tests__/DrawingModeController-test.js, src/doc/DocAnnotator.js, src/doc/__tests__/DocAnnotator-test.js, src/util.js
* Chore: Render/hide annotations from controller
* Chore: Remove references to annotator.threads
* Chore: Remove util.addThreadFromMap/removeThreadFromMap
Tests + jsdocs to come later
=> Chore: Move threadmap entirely to mode controllers 

src/controllers/DrawingModeController.js, src/controllers/__tests__/DrawingModeController-test.js
Fixes issue reported in https://github.com/box/box-annotations/issues/86
=> Fix: Uncaught errors in drawingModeController.handleSelection()

src/AnnotationDialog.js, src/AnnotationThread.js, src/__tests__/AnnotationThread-test.js, src/constants.js, src/controllers/AnnotationModeController.js, src/controllers/DrawingModeController.js, src/controllers/HighlightModeController.js, src/controllers/__tests__/AnnotationModeController-test.js, src/controllers/__tests__/DrawingModeController-test.js, src/controllers/__tests__/HighlightModeController-test.js, src/doc/DocAnnotator.js, src/doc/DocDrawingThread.js, src/doc/DocHighlightThread.js, src/doc/__tests__/DocAnnotator-test.js, src/doc/__tests__/DocDrawingThread-test.js, src/doc/__tests__/DocHighlightThread-test.js, src/drawing/DrawingThread.js, src/drawing/__tests__/DrawingThread-test.js
- More efficient when determining which highlight thread is being hovered over
- Chore: Determine hovered/clicked highlight by tree search
- docs + tests to come
=> New: Store all page highlight threads as an rbush tree

build/current_version.sh, build/publish.sh, build/release.sh
-x flag adds some verbose logging for commands, -e flag exits script on any command which returns non 0
=> Chore: add flags to bash scripts to bail on errors

src/BoxAnnotations.js
This reverts commit 49946991527a777fea4f2bfa025355945aaa0217.
=> Revert "New: Enable draw annotations by default (#115)"

src/Annotation.js, src/AnnotationDialog.js, src/AnnotationThread.js, src/__tests__/AnnotationDialog-test.js, src/__tests__/AnnotationThread-test.js, src/doc/DocHighlightDialog.js, src/doc/__tests__/DocHighlightDialog-test.js
- This can be handled based off of the isPending prop on individual annotations
=> Chore: Remove dialog.enable()/disable()

src/doc/CreateHighlightDialog.js
Matches change for DocHighlightThread https://github.com/box/box-annotations/pull/256
=> Fix: create highlight popover Y positioning

build/webpack.selenium.config.js, functional-tests/helpers/actions.js, functional-tests/helpers/constants.js, functional-tests/helpers/validation.js, functional-tests/tests/draw.js, functional-tests/tests/highlight_comment.js, functional-tests/tests/plain_highlight.js, functional-tests/tests/point.js
Dependent on https://github.com/box/box-annotations/pull/299
=> Fix: Functional tests to work with React components

src/drawing/DrawingThread.js, src/drawing/__tests__/DrawingThread-test.js
=> Fix: Fix position of popover on drawing undo/redo

docs/index.html, package.json, test/index.html, yarn.lock
This should be the last pull request to update dependencies.
=> chore(deps): Upgrade preview and production dependencies

i18n/en-US.properties, jest.config.js, package.json, scripts/jest/popperMock.js, src/@types/global.ts, src/components/AnnotationTarget/__tests__/AnnotationTarget-test.tsx, src/components/Popups/Popper.ts, src/components/Popups/PopupBase.tsx, src/components/Popups/PopupReply.tsx, src/components/Popups/__tests__/Popper-test.ts, src/components/Popups/__tests__/PopupBase-test.tsx, src/components/Popups/__tests__/PopupReply-test.tsx, src/components/Popups/messages.ts, yarn.lock
These popups aren't in use yet, but will be used by the RegionAnnotations component soon.
=> feat(region): Add annotation popup components and tests

src/components/Popups/PopupBase.scss, src/components/Popups/PopupReply.scss
I kinda sorta missed adding these to the last commit. Whoops!
=> feat(region): Add popup component stylesheets

jest.config.js, src/@types/index.ts, src/@types/model.ts, src/common/__mocks__/withProviders.tsx, src/region/RegionAnnotations.tsx, src/region/RegionContainer.tsx, src/region/__tests__/RegionAnnotations-test.tsx, src/region/__tests__/RegionContainer-test.tsx, src/region/__tests__/actions-test.ts, src/region/actions.ts, src/store/annotations/__tests__/actions-test.ts, src/store/annotations/__tests__/reducer-test.ts, src/store/annotations/actions.ts, src/store/annotations/reducer.ts, src/store/creator/__mocks__/creatorState.ts, src/store/creator/__tests__/reducer-test.ts, src/store/creator/reducer.ts, src/store/creator/types.ts
I also fixed a couple of response type properties that were accidentally camelCased during codegen.
=> feat(region): Improve annotation create action async flow

src/@types/events.ts, src/@types/index.ts, src/common/BaseAnnotator.ts, src/common/EventManager.ts, src/common/__tests__/BaseAnnotator-test.ts, src/document/DocumentAnnotator.ts, src/store/annotations/__mocks__/annotationsState.ts, src/store/annotations/__tests__/reducer-test.ts, src/store/annotations/__tests__/selectors-test.ts, src/store/annotations/actions.ts, src/store/annotations/reducer.ts, src/store/annotations/selectors.ts, src/store/annotations/types.ts, src/store/eventing/__tests__/active-test.ts, src/store/eventing/__tests__/create-test.ts, src/store/eventing/active.ts, src/store/eventing/create.ts, src/store/eventing/middleware.ts, src/store/eventing/types.ts
=> feat(eventing): set active annotation

src/@types/model.ts, src/region/RegionAnnotations.tsx, src/region/RegionContainer.tsx, src/region/__mocks__/data.ts, src/region/__tests__/RegionAnnotations-test.tsx, src/region/__tests__/RegionContainer-test.tsx, src/store/eventing/__tests__/create-test.ts, src/store/eventing/create.ts
=> feat(activeannotation): apply activeId to existing annotation

package.json, yarn.lock
Looks like we got a little ahead of ourselves.
=> chore(deps): Reduce required versions of react and yarn

src/components/Popups/PopupBase.scss, src/components/Popups/PopupReply.scss, src/components/Popups/PopupReply.tsx, src/components/Popups/__tests__/PopupReply-test.tsx
* Update style for primary button in pop-up
* Disable post button if popup value is empty
* Update test for PopupReply
=> feat(popup): update disabled state

package.json, scripts/jest/enzyme-adapter.js, src/components/AutoScroller/AutoScroller.tsx, src/components/AutoScroller/__tests__/AutoScroller-test.tsx, src/components/AutoScroller/__tests__/util-test.ts, src/components/AutoScroller/index.ts, src/components/AutoScroller/util.ts, src/components/Popups/Popper.ts, src/components/Popups/PopupBase.tsx, src/components/Popups/PopupReply.tsx, src/region/RegionAnnotation.scss, src/region/RegionAnnotation.tsx, src/region/RegionAnnotations.scss, src/region/RegionAnnotations.tsx, src/region/RegionCreator.scss, src/region/RegionCreator.tsx, src/region/RegionRect.scss, src/region/RegionRect.tsx, src/region/__tests__/RegionAnnotation-test.tsx, src/region/__tests__/RegionAnnotations-test.tsx, src/region/__tests__/RegionCreator-test.tsx, src/region/__tests__/RegionRect-test.tsx
=> feat(region): Add support for autoscroll during region draw

.eslintrc.js, src/@types/index.ts, src/@types/users.ts, src/api/APIFactory.ts, src/api/types.ts, src/common/BaseAnnotator.ts, src/common/__tests__/BaseAnnotator-test.ts, src/components/Popups/ReplyField/ReplyField.tsx, src/components/Popups/ReplyField/ReplyFieldContainer.tsx, src/components/Popups/ReplyField/__tests__/ReplyField-test.tsx, src/region/regionUtil.ts, src/store/createRootReducer.ts, src/store/creator/reducer.ts, src/store/eventing/active.ts, src/store/index.ts, src/store/types.ts, src/store/users/__mocks__/usersState.ts, src/store/users/__tests__/reducer-test.ts, src/store/users/__tests__/selectors-test.ts, src/store/users/actions.ts, src/store/users/index.ts, src/store/users/reducer.ts, src/store/users/selectors.ts, src/store/users/types.ts
=> feat(api): Add file collaborators fetch action

package.json, src/api/__mocks__/APIFactory.ts, src/api/types.ts, src/common/BaseAnnotator.ts, src/common/__tests__/BaseAnnotator-test.ts, src/store/annotations/__tests__/actions-test.ts, src/store/annotations/actions.ts, src/store/options/__tests__/reducer-test.ts, src/store/options/__tests__/selectors-test.ts, src/store/options/actions.ts, src/store/options/reducer.ts, src/store/options/selectors.ts, src/store/options/types.ts, yarn.lock
=> feat(permissions): Add permissions object to annotations api calls

i18n/en-US.properties, src/components/Popups/PopupBase.scss, src/components/Popups/PopupCursor.scss, src/components/Popups/PopupCursor.tsx, src/components/Popups/ReplyField/PopupList.scss, src/components/Popups/__tests__/PopupCursor-test.tsx, src/components/Popups/messages.ts, src/region/RegionCreator.tsx, src/region/__tests__/RegionCreator-test.tsx
=> feat(region): Add cursor tooltip

src/@types/model.ts, src/common/BaseAnnotator.ts, src/common/EventEmitter.ts, src/common/__tests__/BaseAnnotator-test.ts, src/common/__tests__/EventEmitter-test.ts, src/common/__tests__/EventManager-test.ts, src/document/DocumentAnnotator.ts, src/document/__tests__/DocumentAnnotator-test.ts, src/region/RegionContainer.tsx, src/region/__mocks__/data.ts, src/region/__tests__/RegionAnnotations-test.tsx, src/region/__tests__/regionUtil-test.ts, src/region/index.ts, src/region/regionUtil.ts
=> fix(scroll): Fix scroll-to-annotation behavior if page isn't rendered

src/@types/events.ts, src/store/eventing/__tests__/fetch-test.ts, src/store/eventing/fetch.ts, src/store/eventing/middleware.ts
=> feat(api): Handle API fetch errors

src/components/ReplyField/ReplyField.scss, src/components/ReplyForm/ReplyButton.tsx, src/components/ReplyForm/ReplyForm.scss, src/components/ReplyForm/ReplyForm.tsx, src/components/ReplyForm/ReplyFormContainer.tsx, src/components/ReplyForm/__tests__/ReplyForm-test.tsx
=> fix(styles): Remove components that import conflicting global styles

src/components/ReplyForm/ReplyForm.tsx, src/components/ReplyForm/__tests__/ReplyForm-test.tsx
=> feat(hotkeys): Press Esc to exit annotations mode

src/common/BaseAnnotator.ts, src/components/ReplyField/ReplyField.tsx, src/components/ReplyField/ReplyFieldContainer.tsx, src/components/ReplyField/__tests__/ReplyField-test.tsx, src/store/users/__tests__/reducer-test.ts, src/store/users/actions.ts
=> feat(mentions): Server-side filtering

src/components/ReplyForm/ReplyButton.tsx, src/components/ReplyForm/__tests__/ReplyButton-test.tsx
Fixes behavioral discrepancy between our buttons and BUIE's.
=> fix(reply): Allow keyboard focus for disabled reply buttons

src/components/ItemList/ItemList.scss, src/components/Popups/PopupList.scss
=> fix(mentions): Fix collabs list too long

src/components/ItemList/ItemList.tsx, src/components/ItemList/ItemRow.tsx, src/components/ItemList/__tests__/ItemList-test.tsx, src/components/Popups/PopupList.tsx, src/components/ReplyField/ReplyField.tsx, src/components/ReplyField/__tests__/ReplyField-test.tsx
=> fix(mentions): Fix collabs list scrolling via keys

src/common/BaseAnnotator.ts, src/common/__tests__/BaseAnnotator-test.ts, src/components/Popups/PopupReply.tsx, src/components/ReplyForm/ReplyForm.tsx, src/components/ReplyForm/ReplyFormContainer.tsx, src/components/ReplyForm/__tests__/ReplyForm-test.tsx, src/components/ReplyForm/__tests__/ReplyFormContainer-test.tsx, src/region/RegionManager.tsx, src/store/options/__tests__/selectors-test.ts, src/store/options/reducer.ts, src/store/options/selectors.ts, src/store/options/types.ts
=> chore(resin): Add resin tags to popup

src/region/RegionAnnotation.tsx, src/region/RegionList.tsx, src/region/__tests__/RegionAnnotation-test.tsx
=> chore(resin): Add resin tags to markups

src/constants.js, src/region/RegionAnnotation.scss, src/region/RegionAnnotation.tsx, src/region/RegionCreator.tsx, src/region/RegionRect.scss, src/region/__tests__/RegionAnnotation-test.tsx, src/utils/scroll.ts
Note: This PR is meant to be accompanied by https://github.com/box/box-ui-elements/pull/2231, though it's not a strict dependency.
=> feat(regions): Improve click, focus, and scroll interactions for regions

src/@types/model.ts, src/BoxAnnotations.ts, src/__tests__/BoxAnnotations-test.js, src/document/DocumentAnnotator.ts, src/document/__tests__/DocumentAnnotator-test.ts, src/highlight/HighlightAnnotation.scss, src/highlight/HighlightAnnotation.tsx, src/highlight/HighlightAnnotations.tsx, src/highlight/HighlightCanvas.scss, src/highlight/HighlightCanvas.tsx, src/highlight/HighlightContainer.tsx, src/highlight/HighlightList.scss, src/highlight/HighlightList.tsx, src/highlight/HighlightManager.tsx, src/highlight/__mocks__/data.ts, src/highlight/__tests__/HighlightAnnotation-test.tsx, src/highlight/__tests__/HighlightAnnotations-test.tsx, src/highlight/__tests__/HighlightCanvas-test.tsx, src/highlight/__tests__/HighlightContainer-test.tsx, src/highlight/__tests__/HighlightList-test.tsx, src/highlight/__tests__/highlightUtil-test.ts, src/highlight/highlightUtil.ts, src/region/RegionList.tsx, src/utils/util.ts
=> feat(highlights): Render highlight annotations

src/highlight/HighlightCanvas.tsx, src/highlight/HighlightList.tsx, src/highlight/HighlightTarget.tsx, src/highlight/__mocks__/HighlightCanvas.tsx, src/highlight/__mocks__/HighlightTarget.tsx, src/highlight/__tests__/HighlightList-test.tsx, src/highlight/__tests__/HighlightTarget-test.tsx
=> feat(highlights): Apply hover effect

src/store/highlight/__mocks__/data.ts, src/store/highlight/__tests__/actions-test.ts, src/store/highlight/__tests__/reducer-test.ts, src/store/highlight/actions.ts
=> fix(range): Fix Range.getClientRects on IE/Edge

src/highlight/HighlightCanvas.tsx
=> feat(highlights): Remove rounded corners

src/document/__tests__/DocumentAnnotator-test.ts, src/store/eventing/__tests__/mode-test.ts, src/store/eventing/middleware.ts, src/store/eventing/mode.ts
Reverts box/box-annotations#582
=> chore(eventing): Add annotations_mode_change event back

src/highlight/HighlightTarget.tsx, src/highlight/__tests__/HighlightTarget-test.tsx
=> fix(highlights): Manually apply focus to highlight target

src/region/RegionCreator.scss
=> fix(cursor): Adjust Region custom cursor position

.eslintrc.js, test/integration/Highlight.e2e.test.js, test/integration/Region.e2e.test.js, test/integration/Sanity.e2e.test.js
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-
https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Triple-slash-directives
=> test(cypress): Add TS type support to Cypress test files

src/image/ImageAnnotator.scss
=> fix(image): Popover should appear above preview controls

src/drawing/DrawingAnnotations.tsx, src/drawing/DrawingAnnotationsContainer.tsx, src/drawing/__tests__/DrawingAnnotations-test.tsx, src/drawing/__tests__/DrawingAnnotationsContainer-test.tsx, src/region/RegionCreation.tsx, src/region/RegionCreationContainer.tsx, src/region/__tests__/RegionCreation-test.tsx, src/region/__tests__/RegionCreationContainer-test.tsx
Before:
After:
Cannot create during pending.
=> fix(creator): Prevent creating during creator pending

i18n/en-US.properties, package.json, src/components/Popups/PopupDrawingToolbar.scss, src/components/Popups/PopupDrawingToolbar.tsx, src/components/Popups/__tests__/PopupDrawingToolbar-test.tsx, src/components/Popups/messages.ts, src/drawing/DrawingAnnotations.tsx, src/drawing/DrawingAnnotationsContainer.tsx, src/drawing/__tests__/DrawingAnnotations-test.tsx, src/drawing/__tests__/DrawingAnnotationsContainer-test.tsx, src/store/drawing/__mocks__/drawingState.ts, src/store/drawing/__tests__/reducer-test.ts, src/store/drawing/actions.ts, src/store/drawing/reducer.ts, src/store/drawing/selectors.ts, src/store/drawing/types.ts, yarn.lock
=> feat(drawing): Support for undo and redo

src/@types/events.ts, src/common/BaseAnnotator.ts, src/common/__tests__/BaseAnnotator-test.ts, src/drawing/DrawingAnnotations.tsx, src/drawing/DrawingAnnotationsContainer.tsx, src/drawing/DrawingCreator.tsx, src/drawing/__tests__/DrawingAnnotations-test.tsx, src/drawing/__tests__/DrawingAnnotationsContainer-test.tsx, src/drawing/__tests__/DrawingCreator-test.tsx, src/store/common/__mocks__/commonState.ts, src/store/common/__tests__/reducer-test.ts, src/store/common/__tests__/selectors-test.ts, src/store/common/actions.ts, src/store/common/reducer.ts, src/store/common/selectors.ts, src/store/common/types.ts
Preview PR: https://github.com/box/box-content-preview/pull/1309
=> feat(drawing): Support drawing colors

package.json, yarn.lock
Before (focused):
After (focused):
=> fix(a11y): Upgrade box-ui-elements to pickup button styles

scripts/webpack.config.js
Updating the alias path for box-annotations-local-data. Looking to fix an issue with deployments.
=> fix(build): change alias path

package.json, scripts/webpack.config.js
Adding en-us as an explicit env value in order to fix deployment issue
=> fix(build): adding language env value

.travis.yml
this will make sure that this package builds properly whenever any new changes are made.
=> ci: add yarn build to CI
